image:
  file: Dockerfile
tasks:
  - command: . .bashrc && echo Demo Bazel && cd ex-bazel && ./run.sh
#  - command: . .bashrc && echo Demo Scan-Build && cd ex-scan-build && ./run.sh
  - command: . .bashrc && echo Demo Checkout && git clone https://github.com/chromium/chromium
